title: Jaylen Cheng
description: 自律，沉稳，而后爱人
author: Jaylen Cheng
post_author: Jaylen Cheng
logo: /img/avatar.png
github: https://github.com/jaylencheng
about: 自律，沉稳，而后爱人
mail: "jaylencheng@outlook.com  jaylencheng@ieee.org"

baseurl: ""
url: "https://jaylencheng.github.io"

allowsearch: false

analytics:
  google: UA-110214503-1
disqus:
  name: jaylencheng

share:
  twitter_username: jaylencheng


enableTags: true
tagarray: []

excerpt_separator: "<!--more-->"
paginate: 30
per_page: 50
paginate_path: "/blog/page:num/"
markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: false
   math_engine: mathjax
gems: [jekyll-paginate, jekyll-gist]

# Content Collection
collections:
  articles:
    output: true

# Content Template
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "Jaylen Cheng"
      permalink: "/post/:title.html"
  - scope:
      path: "_articles"
      type: "articles"
    values:
      layout: "post"
      author: "Jaylen Cheng"
      permalink: "/article/:title.html"
